color:
  brandStrength: 0.6102145619224757
  saturation: 0.7040472
  brandColors:
    - '#0D0403'
    - '#6E421F'
    - '#E9C7CF'
    - '#CF7788'
    - '#1E5C30'
  lightness: 0.7293423
  rhythmicContrast: 0
analytics:
  facebook: null
  google: null
  twitter: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
layout_spectrum: 0.6146712
purpose: []
name: emo75
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.002529511
