layout_spectrum: 0.4563163777347654
favicon: null
name: emo75
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.6102145619224757
  lightness: 0.5304749968927354
  saturation: 0.4813718607183546
  rhythmicContrast: 0
  brandColors:
    - '#0F0F0F'
    - '#6E4304'
    - '#6E6E5D'
    - '#BD6F1F'
typography_spectrum: 0.3077005476225168
